# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/


# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  staticDir2: content/en/static

# Uncomment the lines below to configure your website in a second language.
fa:
  languageCode: fa
  contentDir: content/fa
  staticDir2: content/fa/static
  title: '|\|r|\/|i\/'
  params:
    description: صفحه شخصی آرمین درویش
  menu:
    main:
      - name: درباره
        url: '#about'
        weight: 10
      - name: تجربه
        url: '#experience'
        weight: 30
      - name: پروژه ها
        url: '#projects'
        weight: 60
      - name: مقالات
        url: '#featured'
        weight: 80
      - name: نوشته ها
        url: '#posts'
        weight: 90
      - name: رزومه
        url: static_fa/uploads/ArminDarvish_Resume.pdf
        weight: 100
      - name: گالری
        url: '#gallery'
        weight: 120
      - name: تماس
        url: '#contact'
        weight: 130
