#+OPTIONS: author: nil
#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: ./
#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_lastMod: t
#+hugo_front_matter_format: yaml

* en
:PROPERTIES:
:EXPORT_HUGO_SECTION_FRAG: en
:END:
** posts
:PROPERTIES:
:EXPORT_HUGO_SECTION_FRAG: post
:END:
*** PUBLISH Humble Beginnings      :@software:@webdesign:hugo:netlify:github:
CLOSED: [2023-02-09 Thu 09:40]
:PROPERTIES:
:EXPORT_HUGO_DRAFT: false
:EXPORT_HUGO_SECTION_FRAG: humble_beginnings
:EXPORT_FILE_NAME: index
:TITLE: Humble Beginnings
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :subtitle About this Website and Blog
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :summary The totally necessary "about this blog..." post to introduce this website and blog
:END:

#+begin_src yaml :front_matter_extra t
authors:
  - admin
projects: []
featured: false
commentable: true
image:
  caption: 'This art was generated by AI and /\\r|\\\\/|i|\\\\|'
  focal_point: 'center'
#+end_src
**** *TLDR*
I recently decided to redesign and revive my old website and in the process, I decided that I would like to make a habit of writing blog posts here on my own websites. I'll likely be covering a range of topics mostly around research especially in healthcare technology. I'll also share my experience with software tools and workflows for example "How I am using emacs and ox-hugo to write this post" or "using NLP and python to extract interesting information from patents" and ...

**** *How it all started*
I first started working on this website back in 2013. At the time, I was a PhD student at Drexel University working on solid-state nanopores biosensors. I wanted to make a website to showcase my research portfolio and interests and in the process learn more about web design, HTML and CSS as well. I figured I could host it on Drexel's personal web pages and that's how this project simply started. After some initial research, I thought it would be nice to make the website script-free (only HTML and CSS) and only use my own work meaning that everything from design elements (logos, buttons, etc.) to HTML blocks had to be my own creation and not someone else's work[fn:mywork]! The first draft of the design was ready in a few days, but design and coding took some time especially because I had to learn CSS from scratch and my design was tricky to implement because I had hexagons and diagonal borders which was not straightforward, especially with HTML and CSS only. The first version was published later in 2014 and soon after I added a skeleton for my native-speaking language, Farsi. However, in the meanwhile I got very busy with my PhD research and keeping everything up to date with two languages was simply more work than I anticipated, so the progress slowed down. I then graduated in the middle of 2016 and moved to Northern California to work for a small start-up, where I found myself spending an average of 12–14 hours a day at work[fn:longwork]. That left me with no time to work on any personal projects including this website. 

**** *A New Beginning*
The project was abandoned for years with no updates while I was working for start-up companies in Silicon Valley. Then in 2019, I decided to leave the start-up scene and its ridiculously long working hours for greener pastures in a bigger, more stable company with more humane hours, and once again I found some time to consider personal projects and decided to bring this website back alive. The idea was further reinforced by the fact that the hosting server I was using was shut down by Drexel University. I decided it would be better to use a whole new set of tool chain, since the old website with HTML and CSS was not easy to maintain, plus the fact that this was again a good opportunity to learn new tools and skills. After some brief research I decided that I want to use Hugo combined with GitHub and Netlify[fn:Netlify], and after some more browsing and looking at other people's examples, I decided to give "Academic Hugo" from Wowchemy and the result is what you are looking at.

**** *Going Forward*
Using Hugo and Netlify, made it really easy to update my website in more than one language as well. In fact it is easy enough to update that I have decided I can keep a blog here. In the past I have written scattered notes here and there on different social media platforms but going forward I'd like to keep everything here on my own website. My new goal in this project is to make a habit of writing short posts on interesting topics and build a collection of thought, ideas, tutorials over time. I will likely write about various topics I am interested in like biotech, nanosensors, and healthcare technology.  In addition, I will be writing posts on some software tools like interesting work flows in emacs including the one I am using to make this very post right now or how to use midjourney to make interesting backgrounds for your website, or using python and NLP to extract detailed technical information from Google Patents, and ...

While this is going to be a multilinqual blog, not all posts will be available in all languages.  My thoughts, experiences and perhaps even my personality is not always identical in environments with different languages, and therefore, the contents of my posts will reflect that reality. 


*** DRAFT If ChatGPT can get a Wharton's MBA, why should you? :@software:@AI:chatGPT: 
:PROPERTIES:
:EXPORT_HUGO_DRAFT: true
:EXPORT_HUGO_SECTION_FRAG: chatGPT_MBA
:EXPORT_FILE_NAME: index
:TITLE: If ChatGPT can get a Wharton's MBA, why should you?
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :subtitle 
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :summary 
:END:

* fa
:PROPERTIES:
:EXPORT_LANGUAGE: Farsi
:EXPORT_HUGO_SECTION_FRAG: fa
:END:

** posts
:PROPERTIES:
:EXPORT_HUGO_SECTION_FRAG: post
:END:

*** PUBLISH شروعی ساده
CLOSED: [2023-02-09 Thu 09:40]
:PROPERTIES:
:EXPORT_HUGO_DRAFT: false
:EXPORT_HUGO_SECTION_FRAG: humble_beginnings
:EXPORT_FILE_NAME: index
:TITLE: شروعی ساده
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :subtitle در مورد وبسایت و وبلاگ 
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :summary «معرفی وبسایت»
:END:
#+begin_src yaml :front_matter_extra t
authors:
  - admin
projects: []
featured: false
commentable: true
image:
  caption: 'This is an art made by midjourney AI and Armin'
  focal_point: 'center'
#+end_src

**** *در چند جمله*
من اخیراً تصمیم گرفتم وبسایت قدیمی خود را بازطراحی و احیا کنم و در ادامه تصمیم گرفتم که از این پس نوشته های پراکنده خود را به صورت پست های وبلاگی در همین وبسایت منتشر کنم. به احتمال زیاد موضوعات پستها طیف متنوعی خواهند داشت اما سعی میکنم بیشتر به حوزه تخصص خودم به ویژه تکنولوژی سلامت بپردازم. همچنین دوست دارم تجربیات خودم را در استفاده از ابزارهای نرم افزاری به اشتراک بگذارم، به عنوان مثال پستهایی مثل "چگونه از emacs و ox-hugo برای نوشتن وبلاگ استفاده کنیم" یا "استفاده از NLP و python برای استخراج اطلاعات فنی از گوگل پتنت" و ...

****  *چطور همه چی شروع شد*

من برای اولین بار در سال ۱۳۹۱ شروع به طراحی این وب سایت کردم. در آن زمان، من در دانشگاه درکسل در آمریکا دانشجوی دکترا بودم و در حوزه نانوحفره های مصنوعی به عنوان حسگرهای زیستی مشغول به مطالعه و تحقیق. من می‌خواستم وبسایتی بسازم تا مجموعه تحقیقات و علایقم را به نمایش بگذارم و در این فرآیند درباره طراحی وب، «HTML» و «CSS» نیز اطلاعات بیشتری کسب کنم. وقتی متوجه شدم که می‌توانم وبسایت خود را در فضای صفحه وب شخصی دانشگاه درکسل میزبانی کنم، این پروژه به سادگی شروع شد. پس از تحقیقات اولیه، فکر کردم خوب است که وب سایت را بدون اسکریپت (یعنی فقط با «HTML» و «CSS») طراحی کنم و در عین حال فقط از کار خودم استفاده کنم به این معنی که همه چیز از عناصر طراحی (لوگوها، دکمه ها و غیره) تا بلوک های «HTML» ساخته خودم باشد و نه کار شخص دیگری [fn:کارخودم]! اولین پیش نویس طرح در چند روز آماده شد، اما طراحی و کدنویسی کمی طول کشید، به خصوص به این دلیل که باید CSS را از ابتدا یاد می گرفتم و اجرای طرح اولیه ساده نبود، چرا که از شش ضلعی و حاشیه های مورب استفاده می کرد، که به راحتی قابل اجرا نبود به خصوص اینکه فقط از «HTML» و «CSS» استفاده می کردم. اولین نسخه در سال ۱۳۹۲ منتشر شد و کمی پس از آن نسخه اولیه فارسی  را به وبسایت اضافه کردم. اما در همین حین، من درگیر تحقیقات دکترای خود شدم و به روز نگه داشتن وبسایت با دو زبان بیشتر از آنچه پیش بینی می کردم وقت میبرد، بنابراین پیشرفت کار کند شد. سپس در اواسط سال ۱۳۹۵ فارغ التحصیل شدم و به کالیفرنیای شمالی نقل مکان کردم تا برای یک شرکت کوچک و نوبنیان کار کنم،  جایی که روزانه به طور متوسط ​​بین ۱۲ تا ۱۴ ساعت وقت می‌گذاشتم [fn:کارزیاد].بنابراین دیگر فرصتی برای کار بر روی پروژه های شخصی از جمله این وب سایت نبود.

**** *شروعی تازه*

این پروژه پس از آن برای چند سال بدون به‌روزرسانی رها شد تا اینکه من نهایتاً در سال ۱۳۹۸، تصمیم گرفتم شرکتهای نوپا و ساعات کار طولانی آنها را ترک کنم و به یک شرکت بزرگتر و پایدارتر با ساعات کاری انسانی‌تری بپیوندم. در نتیجه یک بار دیگر این فرصت به وجود آمد که به کار بر روی پروژه های شخصی از جمله این وب سایت بپردازم.  یک بار دیگر فرصتی برای بررسی پروژه‌های شخصی پیدا کردم و تصمیم گرفتم این وبسایت را احیا کنم. ایده احیای وبسایت با این واقعیت که دانشگاه درکسل تصمیم گرفت سروری را که میزبان وبسایت اصلی من بود خاموش کند تقویت شد.در ادامه تصمیم گرفتم که از یک زنجیره ابزار جدید استفاده کنم، زیرا نگهداری وب سایت قدیمی با «HTML» و «CSS» آسان نبود، به علاوه این فرصت خوبی بود برای اینکه دوباره ابزار و مهارت های جدیدی را یاد بگیرم. بعد از کمی تحقیق، تصمیم گرفتم که از «Hugo»، به همراه «GitHub» و «Netlify» استفاده کنم، و بعد از دیدن نمونه های مشابه و توصیه های آنلاین، تصمیم گرفتم از طرح «Academic Hugo» از «Wowchemy» استفاده کنم و نتیجه همین شد که میبینید.

**** *پس از این*

با استفاده از زنجیره ابزار جدید، به روز رسانی این وب سایت بسیار آسانتر شد. در واقع به روزرسانی آنقدر آسان شد که تصمیم گرفتم می توانم یک وبلاگ هم به این پروژه اضافه کنم. پیش اط این من یادداشت‌های پراکنده‌ای را اینجا و آنجا در پلتفرم‌های رسانه‌های اجتماعی مختلف منتشر کرده بودم، اما اکنون می‌خواهم همه چیز را اینجا در وب‌سایت خودم نگه دارم. هدف جدید من در این پروژه این است که عادت کنم به نوشتن پست های کوتاه در مورد موضوعات جالب و ساخت مجموعه ای از افکار، ایده ها، یادداشتها و دستورالعملهایی که به مرور جمع آوری میکنم. احتمالاً در مورد موضوعات مختلفی که به آنها علاقه دارم مانند بیوتکنولوژی، نانوحسگرها و تکنولوژی سلامت خواهم نوشت. همچنین دوست دارم که تجربه خودم از استفاده از  ابزارهای نرم افزاری مانند استفاده از «emacs» مثلاً برای ایجاد همین پست و یا نحوه استفاده از «midjourney» برای ایجاد پس زمینه های جالب برای وب سایت خود، یا استفاده از «python» و «NLP» برای استخراج اطلاعات فنی از پتنت های گوگل و ... بنویسم.

در حالی که این یک وبلاگ چند زبانه خواهد بود، همه پست ها به همه زبان ها در دسترس نخواهند بود و نوشته های فارسی لزوماً ترجمه نوشته های انگلیسی نیست. افکار، تجربیات و شاید حتی شخصیت من در محیط هایی با زبان های مختلف یکسان نیست و بنابراین، مطالب پست های من نیز انعکاس این تجربیات خواهند بود.


* Footnote
* COMMENT Local Variables                          :ARCHIVE:

# Local Variables:
# eval: (org-hugo-auto-export-mode t)
# End:







* Footnotes
[fn:mywork] The only exception was the map widget

[fn:کارخودم] البته به جز بعضی المانهای خاص مثل نقشه!

[fn:کارزیاد]توصیه میکنم که این حد از کار را به هیچ عنوان تجربه نکنید چون برای جسم و مغز و روح و روانتون مضره!

[fn:Netlify]Note to self: write another post about choice of tools and how to build a website with hugo, github and netlify! 

[fn:longwork] I Don't suggest trying that yourself. It's not good for your physical or mental health!


